"""Phase 3 blind-validation location set - LOCKED BEFORE ANY MODEL PREDICTION IS RUN.

None of these locations were used to design, diagnose, or tune V2 (excludes all 19 sites from the
original historical-flood-validation study, all 7 real-parcel-diagnostic locations, and Malam
Madori from the pluvial regression fixture - 20 locations total, retired from validation use per
explicit instruction). Every entry below has a specific documented evidence source and an honestly
disclosed spatial-precision caveat - coordinates are LGA-headquarters/town-centroid estimates from
general geographic knowledge, NOT validated flood-polygon boundaries or surveyed points, exactly
the same "regional proxy, not site-level validation" caveat disclosed throughout this investigation.

DO NOT EDIT THIS FILE AFTER PREDICTIONS HAVE BEEN RUN. If a location needs to be added or removed,
that must happen before scratch/phase3_run_predictions.py is executed - never after, and never in
response to how a location's predicted score turned out.

FLOODED (10) - all documented by NEMA, UNDP, OCHA/ReliefWeb, or direct governor/agency statements
covered by FloodList/CNN, none reused from V1 or V2 development:

- Kogi State, 2022 (Gov. Yahaya Bello, reported via FloodList/CNN; Nigeria's 2022 floods "worst
  flood disaster in a decade" per state government): Ibaji LGA ("almost 100% under water"),
  Ajaokuta LGA, Idah LGA, Igalamela-Odolu LGA, Omala LGA - all along the Niger/Benue confluence
  floodplain, distinct from Lokoja (already used) and from each other.
- Anambra State, 2022 (NEMA / UNDP Nigeria Flood Impact, Recovery and Mitigation Assessment
  Report 2022-2023): Anambra West LGA, Ayamelum LGA - distinct from Ogbaru (already used, same
  state, different LGA).
- Adamawa State, 2022 (NEMA - Kiri/Lagdo Dam release flooding ~12 LGAs along Taraba/Adamawa river
  banks): Fufore LGA - distinct from Numan (already used, same state).
- Yobe State, September 2024 (OCHA "Nigeria: Flood Overview - Borno, Adamawa and Yobe State, 18
  Sept 2024"; Vanguard News): Gujba LGA, Jakusko LGA - bridges/roads destroyed, communities cut
  off from the state capital. A new state entirely, part of the same broader 2024 Alau
  Dam/Borno-Adamawa-Yobe flood event that produced the Maiduguri fixture (already used) but a
  geographically distinct location and community.

CONTROL (10) - non-flooded, evidentiary basis is CLIMATOLOGICAL rather than "no news reports found"
(a stronger basis than the phase-1 study used, per explicit critique that "not known for flooding"
isn't equivalent to a confirmed negative): five in the Köppen BSh hot semi-arid zone (<700mm/year
annual rainfall, a real, citable climate classification - academic source), five on elevated
highland/escarpment terrain distinct from the plateau towns already used (Jos, Obudu, Mambilla):

- Katsina State (Sudano-Sahelian semi-arid, frontline drought-affected state per academic
  climate-zone literature): Katsina city, Daura, Funtua.
- Zamfara State (same semi-arid zone): Gusau, Talata Mafara.
- Nsukka, Enugu State - hilltop/cuesta-escarpment university town, distinct from Enugu city
  (already used, same state, different, lower-lying location).
- Idanre, Ondo State - hill town on a granite inselberg massif, historically a defensive
  highland settlement precisely because of its elevation.
- Kafanchan, Kagoro, Zaria, Kaduna State - southern Kaduna highland belt (a westward extension
  of the Jos Plateau) and the historic elevated walled city of Zaria.

Run: python scratch/phase3_locations.py   (prints the locked list for inspection only - does not
call Earth Engine or compute anything)
"""

LOCATIONS = [
    # --- FLOODED --------------------------------------------------------------------------------
    {
        "name": "Ibaji LGA (Kogi State)", "lat": 6.9667, "lon": 6.6667, "group": "flooded",
        "event_date": "2022-09/10", "source": "Gov. Yahaya Bello statement, reported by FloodList/CNN",
        "source_url": "https://floodlist.com/africa/nigeria-floods-kogi-october-2022",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "Reported \"almost 100% under water\" by the state governor.",
    },
    {
        "name": "Ajaokuta LGA (Kogi State)", "lat": 7.5667, "lon": 6.6667, "group": "flooded",
        "event_date": "2022-09/10", "source": "Gov. Yahaya Bello statement, reported by FloodList/CNN",
        "source_url": "https://floodlist.com/africa/nigeria-floods-kogi-october-2022",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "One of 9 Kogi LGAs confirmed flooded along the Niger/Benue confluence.",
    },
    {
        "name": "Idah LGA (Kogi State)", "lat": 7.1091, "lon": 6.7386, "group": "flooded",
        "event_date": "2022-09/10", "source": "Gov. Yahaya Bello statement, reported by FloodList/CNN",
        "source_url": "https://floodlist.com/africa/nigeria-floods-kogi-october-2022",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "River-Niger port town, one of 9 Kogi LGAs confirmed flooded.",
    },
    {
        "name": "Igalamela-Odolu LGA (Kogi State)", "lat": 7.2667, "lon": 6.9167, "group": "flooded",
        "event_date": "2022-09/10", "source": "Gov. Yahaya Bello statement, reported by FloodList/CNN",
        "source_url": "https://floodlist.com/africa/nigeria-floods-kogi-october-2022",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "One of 9 Kogi LGAs confirmed flooded.",
    },
    {
        "name": "Omala LGA (Kogi State)", "lat": 7.4667, "lon": 7.2333, "group": "flooded",
        "event_date": "2022-09/10", "source": "Gov. Yahaya Bello statement, reported by FloodList/CNN",
        "source_url": "https://floodlist.com/africa/nigeria-floods-kogi-october-2022",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "One of 9 Kogi LGAs confirmed flooded.",
    },
    {
        "name": "Anambra West LGA (Anambra State)", "lat": 6.2500, "lon": 6.6500, "group": "flooded",
        "event_date": "2022", "source": "NEMA / UNDP Nigeria Flood Impact, Recovery and Mitigation Assessment Report 2022-2023",
        "source_url": "https://www.undp.org/nigeria/publications/nigeria-flood-impact-recovery-and-mitigation-assessment-report-2022-2023",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "One of 6 Anambra LGAs named as affected/displaced (651,053 people across those 6 LGAs).",
    },
    {
        "name": "Ayamelum LGA (Anambra State)", "lat": 6.3667, "lon": 6.8500, "group": "flooded",
        "event_date": "2022", "source": "NEMA / UNDP Nigeria Flood Impact, Recovery and Mitigation Assessment Report 2022-2023",
        "source_url": "https://www.undp.org/nigeria/publications/nigeria-flood-impact-recovery-and-mitigation-assessment-report-2022-2023",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "One of 6 Anambra LGAs named as affected/displaced.",
    },
    {
        "name": "Fufore LGA (Adamawa State)", "lat": 9.3000, "lon": 12.6500, "group": "flooded",
        "event_date": "2022", "source": "NEMA - Kiri/Lagdo Dam release flooding along Taraba/Adamawa river banks",
        "source_url": "https://www.icirnigeria.org/lagdo-dam-not-entirely-responsible-for-2022-flooding-nema/",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "Named as one of the most affected Adamawa LGAs alongside Yobe's Gujba/Geidam/Gulani.",
    },
    {
        "name": "Gujba LGA (Yobe State)", "lat": 11.6000, "lon": 11.8667, "group": "flooded",
        "event_date": "2024-09", "source": "OCHA Nigeria Flood Overview - Borno, Adamawa and Yobe State (18 Sept 2024); Vanguard News",
        "source_url": "https://www.unocha.org/publications/report/nigeria/nigeria-flood-overview-borno-adamawa-and-yobe-state-18-september-2024",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "Bridges/roads destroyed; part of the 12 Yobe LGAs cut off from the state capital.",
    },
    {
        "name": "Jakusko LGA (Yobe State)", "lat": 12.2500, "lon": 10.6167, "group": "flooded",
        "event_date": "2024-09", "source": "OCHA Nigeria Flood Overview - Borno, Adamawa and Yobe State (18 Sept 2024); Vanguard News",
        "source_url": "https://www.unocha.org/publications/report/nigeria/nigeria-flood-overview-borno-adamawa-and-yobe-state-18-september-2024",
        "precision": "LGA headquarters/town-centroid estimate, not a validated flood-polygon boundary",
        "note": "Culvert collapse on the Potiskum-Jakusko road; part of the 12 cut-off Yobe LGAs.",
    },
    # --- CONTROL ----------------------------------------------------------------------------------
    {
        "name": "Katsina city (Katsina State)", "lat": 12.9908, "lon": 7.6018, "group": "control",
        "event_date": "n/a", "source": "Köppen BSh hot semi-arid climate zone, <700mm/yr annual rainfall - academic climate-zone literature",
        "source_url": "https://www.earth-site.co.uk/Education/climate-zones-of-nigeria-different-climate-regions-of-nigeria/",
        "precision": "City-centroid estimate",
        "note": "Frontline Sudano-Sahelian drought-affected state.",
    },
    {
        "name": "Daura (Katsina State)", "lat": 13.0333, "lon": 8.3167, "group": "control",
        "event_date": "n/a", "source": "Köppen BSh hot semi-arid climate zone, <700mm/yr annual rainfall",
        "source_url": "https://www.earth-site.co.uk/Education/climate-zones-of-nigeria-different-climate-regions-of-nigeria/",
        "precision": "Town-centroid estimate",
        "note": "Same semi-arid zone as Katsina city.",
    },
    {
        "name": "Funtua (Katsina State)", "lat": 11.5167, "lon": 7.3167, "group": "control",
        "event_date": "n/a", "source": "Köppen BSh hot semi-arid climate zone, <700mm/yr annual rainfall",
        "source_url": "https://www.earth-site.co.uk/Education/climate-zones-of-nigeria-different-climate-regions-of-nigeria/",
        "precision": "Town-centroid estimate",
        "note": "Same semi-arid zone as Katsina city.",
    },
    {
        "name": "Gusau (Zamfara State)", "lat": 12.1700, "lon": 6.6600, "group": "control",
        "event_date": "n/a", "source": "Köppen BSh hot semi-arid climate zone, <700mm/yr annual rainfall",
        "source_url": "https://www.earth-site.co.uk/Education/climate-zones-of-nigeria-different-climate-regions-of-nigeria/",
        "precision": "City-centroid estimate",
        "note": "State capital, frontline drought-affected state.",
    },
    {
        "name": "Talata Mafara (Zamfara State)", "lat": 12.5667, "lon": 6.0667, "group": "control",
        "event_date": "n/a", "source": "Köppen BSh hot semi-arid climate zone, <700mm/yr annual rainfall",
        "source_url": "https://www.earth-site.co.uk/Education/climate-zones-of-nigeria-different-climate-regions-of-nigeria/",
        "precision": "Town-centroid estimate",
        "note": "Same semi-arid zone as Gusau.",
    },
    {
        "name": "Nsukka (Enugu State)", "lat": 6.8583, "lon": 7.3958, "group": "control",
        "event_date": "n/a", "source": "Geographic/topographic - hilltop cuesta-escarpment town",
        "source_url": "",
        "precision": "Town-centroid estimate; elevation basis is general geographic knowledge, not a cited academic source",
        "note": "Distinct from Enugu city (already used in V2 development, different, lower-lying location in the same state).",
    },
    {
        "name": "Idanre (Ondo State)", "lat": 7.1167, "lon": 5.1083, "group": "control",
        "event_date": "n/a", "source": "Geographic/topographic - hill town on a granite inselberg massif",
        "source_url": "",
        "precision": "Town-centroid estimate; elevation basis is general geographic knowledge, not a cited academic source",
        "note": "Historically settled specifically for its elevation/defensibility.",
    },
    {
        "name": "Kafanchan (Kaduna State)", "lat": 9.5833, "lon": 8.3000, "group": "control",
        "event_date": "n/a", "source": "Geographic/topographic - southern Kaduna highland belt (westward Jos Plateau extension)",
        "source_url": "",
        "precision": "Town-centroid estimate; elevation basis is general geographic knowledge, not a cited academic source",
        "note": "",
    },
    {
        "name": "Kagoro (Kaduna State)", "lat": 9.6167, "lon": 8.4167, "group": "control",
        "event_date": "n/a", "source": "Geographic/topographic - southern Kaduna highland belt",
        "source_url": "",
        "precision": "Town-centroid estimate; elevation basis is general geographic knowledge, not a cited academic source",
        "note": "",
    },
    {
        "name": "Zaria (Kaduna State)", "lat": 11.0667, "lon": 7.7000, "group": "control",
        "event_date": "n/a", "source": "Geographic/topographic - historic elevated walled city, northern semi-arid transition zone",
        "source_url": "",
        "precision": "City-centroid estimate; elevation basis is general geographic knowledge, not a cited academic source",
        "note": "",
    },
]


if __name__ == "__main__":
    flooded = [l for l in LOCATIONS if l["group"] == "flooded"]
    control = [l for l in LOCATIONS if l["group"] == "control"]
    print(f"Locked location set: {len(flooded)} flooded, {len(control)} control, {len(LOCATIONS)} total\n")
    for l in LOCATIONS:
        print(f"  [{l['group']}] {l['name']} ({l['lat']}, {l['lon']}) - {l['source']}")
